WIP: Implement `Open`, `Teardown` and `Write` (insert) methods
ConduitIO/conduit-connector-materialize pull request #2
Opened 2022-04-27 15:28 UTC by alyakimenko

### Description

- Implement `Write` method (insert)
- Test the `Write` method
- Implement `Teardown` method
- Update golangci-lint, enable `godot`, `lll` and `nlreturn` linters

### Quick checks:

- [x] I have followed the [Code Guidelines](https://github.com/ConduitIO/conduit/blob/main/docs/code_guidelines.md).
- [x] There is no other [pull request](https://github.com/ConduitIO/conduit-connector-s3/pulls) for the same update/change.
- [ ] I have written unit tests.
- [x] I have made sure that the PR is of reasonable size and can be easily reviewed.

2022-04-27 19:40 UTC, maksenius commented on destination/destination.go
> +	var colArgs []string
please move these variable inside var(). 
```
var (
     colArgs []string
     valArgs []any
)
```

2022-04-27 19:40 UTC, maksenius commented on destination/destination.go
> +		if d.config.Table == "" {
As I understand we validate config at the `Configure(context.Context, map[string]string) error` method. Do we want check it one more time? But if it is possible case we have to do you it

2022-04-28 07:06 UTC, alyakimenko commented on destination/destination.go
> +		if d.config.Table == "" {
`Table` and `Key` are not required. For example, if the source is Postgres, it sends us a `table` in metadata, so we can write in different tables within the same destination connector instance. But yeah, perhaps we should make config's `Table` and `Key` required

2022-04-28 07:48 UTC, alyakimenko commented on destination/destination.go
> +		if d.config.Table == "" {
@maksenius I made `Table` and `Key` required and removed the check

2022-04-28 07:59 UTC, maksenius commented on destination/destination.go
> +		return err
please wrap error

2022-04-28 07:59 UTC, maksenius commented on destination/destination.go
> +		return nil, err
please wrap error

2022-04-28 08:09 UTC, alyakimenko commented on destination/destination.go
> +		return nil, err
Done

2022-04-28 08:09 UTC, alyakimenko commented on destination/destination.go
> +		return err
Done

2022-04-28 08:23 UTC, maksenius approved these changes

2022-04-28 16:42 UTC, senseyman requested changes

2022-04-28 16:42 UTC, senseyman commented on destination/destination.go
> +var psql = sq.StatementBuilder.PlaceholderFormat(sq.Dollar)
It would be better to name it like `psqlFormatHolder` or `psqlQueryFormatter`, because in most cases psql naming uses for DB connection variable

2022-04-28 16:44 UTC, alyakimenko commented on destination/destination.go
> +var psql = sq.StatementBuilder.PlaceholderFormat(sq.Dollar)
Renamed

2022-04-28 16:46 UTC, senseyman approved these changes

2022-04-28 16:46 UTC, merged